# Generated by Django 2.1.2 on 2019-01-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined', max_length=255)),
                ('type', models.CharField(choices=[['converter', [['hp', 'heat pump'], ['pv', 'photovoltaic'], ['sol_col', 'solar collector']]], ['storage', [['hp_tank', 'heat pump tank'], ['sol_tank', 'solar storage tank']]], ['distribution', [['inv', 'inverter'], ['dist_pump', 'circulator pump'], ['sol_pump', 'solar pump']]]], default='undefined', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default="This is an example description what the model is doing, how it is implemented and anything else, which might be of interest to know about the model.\n\nThis can be a rather longer text, since it may contain relevant information about the model, which can't be stored elsewhere.")),
                ('params', models.TextField(default="{'param' : 123., 'param_2' : 'abc'}")),
                ('size', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined', max_length=255)),
                ('description', models.TextField(default="This is an example description what the model is doing, how it is implemented and anything else, which might be of interest to know about the model.\n\nThis can be a rather longer text, since it may contain relevant information about the model, which can't be stored elsewhere.")),
                ('result', models.CharField(default='3.0', max_length=255)),
                ('components', models.ManyToManyField(blank=True, to='system.Component')),
            ],
        ),
    ]
