# Generated by Django 2.1.2 on 2019-03-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_configuration_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='Load',
        ),
        migrations.DeleteModel(
            name='Load',
        ),
    ]
