# Generated by Django 2.1.2 on 2019-03-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0010_auto_20190304_1315"),
    ]

    operations = [
        migrations.RenameField(
            model_name="configuration",
            old_name="Household",
            new_name="household",
        ),
    ]
