# Generated by Django 2.1.2 on 2019-04-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_configuration_results_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined', max_length=255)),
                ('occupancy', models.TextField(default='undefined')),
                ('at_home', models.TextField(default='undefined')),
                ('size', models.PositiveSmallIntegerField(default=1)),
                ('data', models.TextField(default='undefined')),
            ],
        ),
    ]
