# Generated by Django 2.1.2 on 2019-04-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Project'),
        ),
    ]
