# Generated by Django 2.1.2 on 2019-04-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_configuration_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='community',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='household',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='Household',
        ),
    ]
